[package]
name = "webtitle"
version = "0.1.0"
edition = "2024"
description = "Fetch the title of a website from a given URL"

[profile.release]
# https://github.com/BurntSushi/ripgrep/blob/master/Cargo.toml
opt-level = 3
debug = "none"
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "fat"
panic = "abort"
incremental = false

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
scraper = "0.22"
url = "2"
anyhow = "1"
